### ISSUE TITLE
Saving project to XML sometimes misses the socket connections

### ISSUE THREAD

**Issue by vgrcs** [aluntzer/gtknodes#16]
Hi,

I've experienced that saving the NodeView configuration to file sometimes loses the socket connections.
The Nodes are saved but not the NodeSockets. In my current setup this happens like 1 in 10 saves.

Best regards,
Vitor

**Comment by aluntzer** [comment]
I was unable reproduce this so far. Can you  provide some example code that generates this error or can you point me to you to the code of yours so I can use it to debug this issue?

**Comment by vgrcs** [comment]
I think this happened becaused my application was closing without knowing if the save operation was completed.

**Comment by aluntzer** [comment]
Ok, let's close this for now
