### ISSUE TITLE
Namespace GtkNodes not available

### ISSUE THREAD

**Issue by ghost** [aluntzer/gtknodes#6]
Hi, firstly thanks for this library! I was able to make and run the calculator example in C, but had issues with running the python example and was getting the error:

> gi.require_version('GtkNodes', '0.1')File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version raise ValueError('Namespace %s not available' % namespace)ValueError: Namespace GtkNodes not available

After a bit of searching, I realized there was a flag that needed to be set to generate the `.typelib` file that is used by python.

`./configure --enable-introspection=yes`

Then it was a matter of making sure the `.typelib` file is somewhere where python can find it:

`export LD_LIBRARY_PATH=/usr/lib`
and 
`export GI_TYPELIB_PATH=/usr/lib/girepository-1.0/` worked for me.

After that it ran well, just thought I would leave this here just in case someone else gets stuck.

Thanks again.

**Comment by aluntzer** [comment]
You're welcome, I hope it is useful to you.

The issue has come up before, so I've added a note to the README.

**Comment by ghost** [comment]
Yes, I want to make a basic flow graph for shaders, my inspiration being from this video https://www.youtube.com/watch?v=82AMwQGjc8Y, and this library seems like a perfect fit. Thanks again :)
