### ISSUE TITLE
checking for gobject-introspection... configure: error: gobject-introspection-1.0 is not installed

### ISSUE THREAD

**Issue by ghost** [aluntzer/gtknodes#8]
I had an issue where upon running `./ configure` I got the error:

`checking for gobject-introspection... configure: error: gobject-introspection-1.0 is not installed`

but then when I tried installing with `sudo apt install gobject-introspection` it says it is already installed:

`gobject-introspection is already the newest version (1.64.1-1~ubuntu20.04.1).`

The fix which I found [here](https://forums.linuxmint.com/viewtopic.php?t=95067) was to install `libgirepository1.0-dev`:

`sudo apt install libgirepository1.0-dev`

and then every worked fine. My suggestion is to possibly include `libgirepository1.0-dev` in the dependencies.

Thanks.

**Comment by aluntzer** [comment]
Added,  thanks for the info!
